[theme]

# Primary accent for interactive elements
primaryColor = '#15c67c'

# Background color for the main content area
backgroundColor = '#011F26'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#127369'

# Color used for almost all text
textColor = '#FFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
